version: '3.4'

services:
  db:
    image: mariadb:10.11
    env_file:
      - environment/prod/mariadb.env
    ports:
      - ${MYSQL_PUBLIC_PORT}:3306
    volumes:
      - mysqldata-prod:/var/lib/mysql
      # - ./databasesInit/mariadb/prod:/docker-entrypoint-initdb.d:ro      

  # yarn:
  #   image: node:14
  #   env_file:
  #     - environment/prod/yarn.env
  #   volumes:
  #     - ../app:/var/www/app
  #   working_dir: /var/www/app
  #   command: bash -c "yarn install && yarn build"

  http:
    build:
      context: ../
      dockerfile: docker/http/prod/Dockerfile
      args:
        REACT_APP_API_EP_URI: ${REACT_APP_API_EP_URI}
    env_file:
      - environment/global.env    
      - environment/prod/http.env
    # command: gunicorn --bind 0.0.0.0:80 app:app
    # command: tail -f /dev/null
    # volumes:
    #   - ../api/:/usr/src/app
    #   - ../app/build:/usr/src/app/public
    ports:
      - 80:80

volumes:
  mysqldata-prod:
