version: '3.4'

services:
  db:
    image: mariadb:10.11
    env_file:
      - environment/dev/mariadb.env
    ports:
      - ${MYSQL_PUBLIC_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
      #- ./databasesInit/mariadb/dev/entrypoint:/docker-entrypoint-initdb.d:ro
      - ./databasesInit/mariadb/dev/data:/db/data/

  http:
    build:
      context: ../
      dockerfile: docker/http/dev/Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    env_file:
      - environment/global.env    
      - environment/dev/http.env
    #command: gunicorn --bind 0.0.0.0:5000 wsgi:run_app
    #command : flask run -h 0.0.0.0 -p 5000
    command : python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m flask run -h 0.0.0.0 -p 5000
    #command: tail -f /dev/null
    volumes:
      - ../api/:/usr/src/app
    ports:
      - 5000:5000
      - 5678:5678

  yarn:
    image: node:18
    env_file:
      - environment/dev/yarn.env
    volumes:
      - ../app:/var/www/app
    working_dir: /var/www/app
    ports:
      - 127.0.0.1:3000:3000
      - 9222:9222
    command: bash -c "yarn install && yarn start"
    #command: bash -c "tail -f /dev/null"


volumes:
  mysql-data:
