
on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          file: ./docker/http/prod/Dockerfile
          build-args: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            SECRET_KEY_AES=${{ secrets.SECRET_KEY_AES }}
            SQLALCHEMY_DATABASE_URI=${{ secrets.SQLALCHEMY_DATABASE_URI }}
            GHCR_PAT=${{ secrets.GHCR_PAT }}
          push: true
          tags: ghcr.io/systemefriche/complete-rest-api-flask-with-tests:latest,ghcr.io/systemefriche/complete-rest-api-flask-with-tests:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_DOKKU_HOST }}
          username: ${{ secrets.VPS_DOKKU_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{secrets.VPS_DOKKU_PORT}}
          fingerprint: ${{secrets.VPS_DOKKU_FINGERPRINT}}
          script: |
            echo $GHCR_PAT | docker login ghcr.io -u systemefriche --password-stdin
            docker pull ghcr.io/systemefriche/complete-rest-api-flask-with-tests:latest
            dokku git:from-image complete-rest-api-flask-with-tests ghcr.io/systemefriche/complete-rest-api-flask-with-tests:latest
            dokku ps:rebuild complete-rest-api-flask-with-tests

            # injecter CR_PAT en tant que env var puis exécuter le echo $CR_PAT | docker login ghcr.io -u systemefriche --password-stdin avant docker pull